hostname = vapp.tmuyun.com,gsp.gacmotor.com,mcs-mimp-web.sf-express.com

# 今日越城 v1.04
# 17 8-20/3 * * * https://raw.githubusercontent.com/leafTheFish/DeathNote/main/jryc.js, tag=今日越城, enabled=true
# https://github.com/leafTheFish/DeathNote/blob/main/jryc.js
# [MITM]
# hostname = vapp.tmuyun.com
https://vapp.tmuyun.com/api/user_mumber/account_detail url script-request-header https://raw.githubusercontent.com/leafTheFish/DeathNote/main/jryc.js


#广汽传祺
# [MITM]
# hostname = gsp.gacmotor.com
# 50 8,20 * * * https://raw.githubusercontent.com/leafTheFish/DeathNote/main/gqcq.js, tag=广汽传祺, enabled=true
https://gsp.gacmotor.com/gateway/webapi/account/getUserInfoV2 url script-request-header https://raw.githubusercontent.com/leafTheFish/DeathNote/main/gqcq.js


#顺丰速运
# 51 8,21 * * * https://raw.githubusercontent.com/leafTheFish/DeathNote/main/sfsy.js, tag=顺丰速运, enabled=true
# [MITM]
# hostname = mcs-mimp-web.sf-express.com
https://mcs-mimp-web.sf-express.com/mcs-mimp/share url script-request-header https://raw.githubusercontent.com/leafTheFish/DeathNote/main/sfsy.js
