hostname = me-api.jd.com,api-dd.jd.com,api.m.jd.com,vapp.tmuyun.com,gsp.gacmotor.com,mcs-mimp-web.sf-express.com

^https:\/\/me-api\.jd\.com\/user_new\/info\/GetJDUserInfoUnion url script-request-header https://raw.githubusercontent.com/xqa/quanx/main/Script/ql_sync.js
^https:\/\/api\.m\.jd\.com\/openUpgrade url script-request-header https://raw.githubusercontent.com/xqa/quanx/main/Script/ql_sync.js
^https:\/\/api\-dd\.jd\.com\/client\.action\?functionId=getSessionLog url script-request-header https://raw.githubusercontent.com/xqa/quanx/main/Script/ql_sync.js


https://vapp.tmuyun.com/api/user_mumber/account_detail url script-request-header http://192.168.2.143:5500/ql_sync.js
https://gsp.gacmotor.com/gateway/webapi/account/getUserInfoV2 url script-request-header http://192.168.2.143:5500/ql_sync.js
https://mcs-mimp-web.sf-express.com/mcs-mimp/share url script-request-header http://192.168.2.143:5500/ql_sync.js